### ISSUE TITLE
(Ubuntu x86_64) Segmentation Fault Running Q4_1_O Model

### ISSUE THREAD

**Issue by cryscan** [saharNooby/rwkv.cpp#32] opened 2023-04-18 14:32 UTC
System: Ubuntu 20.04.6 LTS
GCC: 9.4.0
CPU: Intel(R) Xeon(R) Platinum 8358P

Issue:
```bash
$ python rwkv/chat_with_bot.py /path/to/models/Raven-14B-v9-Q4.bin 
Loading 20B tokenizer
System info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
Loading RWKV model
Processing 92 prompt tokens, may take a while
Segmentation fault (core dumped)
```

**Comment by saharNooby** [comment] 2023-04-18 15:52
Can it be reproduced with 169M model?

**Comment by BuilderGuy1** [comment] 2023-04-18 22:47
I'm having the same issue with Apple Silicon. I tested latest 14B & 7B, each with all 3 quantization options. I even tried with 3B v10 Q4_1_0.

**Comment by dmahurin** [comment] 2023-04-19 04:19
Same issue on Apple M2, with all revisions with the Q4_1_0.

**Comment by poisson-fish** [comment] 2023-04-19 18:23
confirm this issue under Arch WSL with `RWKV-4-Raven-14B-v9-Eng99%-Other1%-20230412-ctx8192_q4_1_0.bin`

**Comment by L-M-Sherlock** [comment] 2023-04-20 04:29
I also encounter this problem in my mac m1. Tried 7B and 3B. It occurred before `Processing 92 prompt tokens`.

**Comment by saharNooby** [comment] 2023-04-20 05:35
Probably address misalignment. I'm working on it in https://github.com/saharNooby/rwkv.cpp/pull/33

**Comment by saharNooby** [comment] 2023-04-20 06:04
Alignment fix merged. Please **clone the repo from scratch** and try again:

`git clone --recursive https://github.com/saharNooby/rwkv.cpp.git`

**Comment by L-M-Sherlock** [comment] 2023-04-20 06:17
Thanks! #33 solved my problem. But another bug appeared. The bot only repeats,`> Bob: Hello, Bob.`.

![image](https://user-images.githubusercontent.com/32575846/233274661-14517883-c8fb-43d1-a64d-ea6792048dd8.png)

**Comment by saharNooby** [comment] 2023-04-20 06:36
@BuilderGuy1 @poisson-fish @dmahurin If possible, can you also confirm that segfault is fixed?

@L-M-Sherlock Thanks for the input. Looks like default prompt is not good for Raven, related issue is https://github.com/saharNooby/rwkv.cpp/issues/22

**Comment by dmahurin** [comment] 2023-04-20 06:51
Thanks @saharNooby. It works now on Apple M2 with 3B and 169M.

**Closed** 2023-04-20 10:47 UTC

**Comment by poisson-fish** [comment] 2023-04-20 18:35
sorry for late reply @saharNooby, the previous crash is fixed however now I get SIGSEGV:

```
python rwkv/chat_with_bot.py ./build/models/RWKV/RWKV-4-Raven-14B-v9-Eng99\%-Other1\%-20230412-ctx8192_q4_1
_0.bin
Loading 20B tokenizer
System info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
Loading RWKV model
Processing 92 prompt tokens, may take a while
~/Documents/Projects/cpp/llamapi/rwkv.cpp/rwkv/rwkv_cpp_model.py:100: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  state_out.storage().data_ptr(),
~/Documents/Projects/cpp/llamapi/rwkv.cpp/rwkv/rwkv_cpp_model.py:101: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  logits_out.storage().data_ptr()
fish: Job 1, 'python rwkv/chat_with_bot.py ./…' terminated by signal SIGSEGV (Address boundary error)```
